[versions]
jupiter = "5.11.3"
shadow = "8.3.5"
spigot-legacy = "1.7.2-R0.1-SNAPSHOT"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
jupiter = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
spigot-legacy = { module = "org.spigotmc:spigot-api", version.ref = "spigot-legacy" }